USER_SRC = allocator.hpp define.hpp message.hpp symtab.hpp types.hpp user.hpp deserialiser.hpp deserialise_message_meta.hpp
USER_SRC += net/common.hpp net/net.hpp

format:
	clang-format -i $(USER_SRC)
