USER_SRC = allocator.hpp define.hpp message.hpp latency_tool.hpp symtab.hpp types.hpp user.hpp deserialiser.hpp deserialise_message_meta.hpp string_pool.hpp thread_pool.hpp lockless_ringBuffer.hpp
USER_SRC += net/common.hpp net/net.hpp

format:
	clang-format -i $(USER_SRC)
